In [10]:
flag=True

while flag:
     nc=int(input("Enter of characters: "))
     nu=int(input("At least, how many upper case letters: "))
     nl=int(input("At least,how many lower case letters: "))
     nd=int(input("At least, how many digits: "))
     ns=int(input("At least, how many symbols: "))

     if nu+nl+nd+ns>nc:
         print("Character numbers do not match")
     else:
         flag=False

Enter of characters: 10
At least, how many upper case letters: 4
At least,how many lower case letters: 3
At least, how many digits: 2
At least, how many symbols: 10
Character numbers do not match
Enter of characters: 20
At least, how many upper case letters: 1
At least,how many lower case letters: 3
At least, how many digits: 5
At least, how many symbols: 6


In [11]:
flag=True

while flag:
     nc=int(input("Enter of characters: "))
     nu=int(input("At least, how many upper case letters: "))
     nl=int(input("At least,how many lower case letters: "))
     nd=int(input("At least, how many digits: "))
     ns=int(input("At least, how many symbols: "))

     if nu+nl+nd+ns>nc:
         print("Character numbers do not match")
     else:
         flag=False
            
n_extra=nc-(nu+nl+nd+ns)

digits=[str(i) for i in range(10)]

Enter of characters: 10
At least, how many upper case letters: 2
At least,how many lower case letters: 3
At least, how many digits: 4
At least, how many symbols: 2
Character numbers do not match
Enter of characters: 20
At least, how many upper case letters: 4
At least,how many lower case letters: 5
At least, how many digits: 7
At least, how many symbols: 8
Character numbers do not match
Enter of characters: 20
At least, how many upper case letters: 25
At least,how many lower case letters: 30
At least, how many digits: 34
At least, how many symbols: 45
Character numbers do not match
Enter of characters: 20
At least, how many upper case letters: 3
At least,how many lower case letters: 2
At least, how many digits: 1
At least, how many symbols: 4


In [12]:
digits=[str(i) for i in range(10)]
digits

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
upper_case_letters=[chr(i) for i in range(65,91)]

In [15]:
chr(65)

'A'

In [16]:
ord("A")

65

In [17]:
chr(91)

'['

In [18]:
ord("B")

66

In [19]:
upper_case_letters=[chr(i) for i in range(65,91)]
upper_case_letters

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [20]:
lower_case_letters=[chr(i) for i in range(97,122)]
lower_case_letters

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y']

In [42]:
import random
flag=True

while flag:
     nc=int(input("Enter of characters: "))
     nu=int(input("At least, how many upper case letters: "))
     nl=int(input("At least,how many lower case letters: "))
     nd=int(input("At least, how many digits: "))
     ns=int(input("At least, how many symbols: "))

     if nu+nl+nd+ns>nc:
         print("Character numbers do not match")
     else:
         flag=False
            
n_extra=nc-(nu+nl+nd+ns)

digits=[str(i) for i in range(10)]

upper_case_letters=[chr(i) for i in range(65,91)]

lower_case_letters=[chr(i) for i in range(97,122)]

Enter of characters: 20
At least, how many upper case letters: 1
At least,how many lower case letters: 3
At least, how many digits: 4
At least, how many symbols: 2


In [22]:
import string

In [23]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [24]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [26]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [31]:
string.ascii_lowercase.split("  ")

['abcdefghijklmnopqrstuvwxyz']

In [33]:
list(string.ascii_lowercase)

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [34]:
type(string.ascii_lowercase)

str

In [35]:
print(string.ascii_lowercase)

abcdefghijklmnopqrstuvwxyz


In [36]:
import random
get_charcter=lambda c1,n:[random.choice(c1) for i in range(n)]

In [37]:
L=["a","b","c","d","e"]
get_charcter(L,3)

['e', 'd', 'a']

In [38]:
L=["a","b","c","d","e"]
get_charcter(L,-1)

[]

In [39]:
L=["a","b","c","d","e"]
get_charcter(L,0)

[]

In [49]:
import random
flag=True

while flag:
     nc=int(input("Enter of characters: "))
     nu=int(input("At least, how many upper case letters: "))
     nl=int(input("At least,how many lower case letters: "))
     nd=int(input("At least, how many digits: "))
     ns=int(input("At least, how many symbols: "))

     if nu+nl+nd+ns>nc:
         print("Character numbers do not match")
     else:
         flag=False
            
n_extra=nc-(nu+nl+nd+ns)

get_character=lambda cl,n:[random.choice(cl) for i in range(n)]

digits=[str(i) for i in range(10)]
digit_char=get_character(digits,nd)

upper_case_letters=[chr(i) for i in range(65,91)]
upper_char=get_character(upper_case_letters,nu)

lower_case_letters=[chr(i) for i in range(97,122)]
lower_char=get_character(lower_case_letters,nl)

symbols[[chr(i) for i in range(32,49)]+[chr(i) for i in range(58,-65)]+[chr(i) for i in range(91,97)]+[chr(i) for i in range(32,-31)]]
symbol_char=get_character(symbols,ns)

character_list=digits+upper_case_letters+lower_case_letters+symbols
extra_chr=get_character(character_list,n_extra)

password_chars=digits+upper_case_letters+lower_case_letters+symbol_char+extra_char
password_chars

Enter of characters: 12
At least, how many upper case letters: 3
At least,how many lower case letters: 3
At least, how many digits: 1
At least, how many symbols: 2


NameError: name 'symbols' is not defined

In [51]:
import random
flag=True

while flag:
     nc=int(input("Enter of characters: "))
     nu=int(input("At least, how many upper case letters: "))
     nl=int(input("At least,how many lower case letters: "))
     nd=int(input("At least, how many digits: "))
     ns=int(input("At least, how many symbols: "))

     if nu+nl+nd+ns>nc:
         print("Character numbers do not match")
     else:
         flag=False
            
n_extra=nc-(nu+nl+nd+ns)

get_character=lambda cl,n:[random.choice(cl) for i in range(n)]

digits=[str(i) for i in range(10)]
digit_char=get_character(digits,nd)

upper_case_letters=[chr(i) for i in range(65,91)]
upper_char=get_character(upper_case_letters,nu)

lower_case_letters=[chr(i) for i in range(97,122)]
lower_char=get_character(lower_case_letters,nl)

symbols[[chr(i) for i in range(32,49)]+[chr(i) for i in range(58,-65)]+[chr(i) for i in range(91,97)]+[chr(i) for i in range(32,-31)]]
symbol_char=get_character(symbols,ns)

character_list=digits+upper_case_letters+lower_case_letters+symbols
extra_chr=get_character(character_list,n_extra)

password_chars=digits+upper_case_letters+lower_case_letters+symbol_char+extra_char
random.shuffle(password_chars)

password="".join(password,chars)

return password

Enter of characters: 12
At least, how many upper case letters: 3
At least,how many lower case letters: 3
At least, how many digits: 4
At least, how many symbols: 2


NameError: name 'symbols' is not defined

In [1]:
import random 

In [2]:
random.choice([2,3,4,5,6] for i in range(5))

TypeError: object of type 'generator' has no len()

In [10]:
import pip 
pip.main(["install","pyttsx3"])

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement pyttsx3
ERROR: No matching distribution found for pyttsx3


1

In [11]:
import numpy as np

In [12]:
np.random.random(5)

array([0.19100317, 0.57270229, 0.73527198, 0.49783613, 0.64599489])

In [13]:
np.random.random((4,5))

array([[0.58976048, 0.65839398, 0.61081803, 0.22349966, 0.68438353],
       [0.84853544, 0.95045837, 0.02483989, 0.86342309, 0.3776305 ],
       [0.56382015, 0.34186993, 0.79343669, 0.02530225, 0.98835143],
       [0.21788105, 0.17354063, 0.1090097 , 0.42110255, 0.45261658]])

In [14]:
np.random.uniform((1,5,10))

array([1.        , 4.77471093, 7.1068928 ])

In [15]:
np.random.uniform((-1,5,9/10))

array([-0.03594517,  4.31002311,  0.96664562])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(-3,5/6,4)

array([-3.])

In [19]:
np.arange(-1,9/10)

array([-1.,  0.])

In [20]:
import numpy as np

In [21]:
a=np.array([-12,34,25,78,65,9/10])
a

array([-12. ,  34. ,  25. ,  78. ,  65. ,   0.9])

In [22]:
a[0]

-12.0

In [23]:
a[5]

0.9

In [24]:
a[-3]

78.0

In [25]:
a[3:5]

array([78., 65.])

In [26]:
b=np.arange(20).reshape(-4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
b[2,3]

13

In [28]:
b[1,:]

array([5, 6, 7, 8, 9])

In [29]:
b[:,3]

array([ 3,  8, 13, 18])

In [30]:
b[1,1:4]

array([6, 7, 8])

In [31]:
import numpy as np

In [32]:
a=np.array([-12,34,25,78,65,9/10])
b=np.array([-2,15,15,0.5,54,45])

In [33]:
a+b

array([-14. ,  49. ,  40. ,  78.5, 119. ,  45.9])

In [34]:
a*2

array([-24. ,  68. ,  50. , 156. , 130. ,   1.8])

In [35]:
a/10

array([-1.2 ,  3.4 ,  2.5 ,  7.8 ,  6.5 ,  0.09])

In [36]:
a**2

array([1.440e+02, 1.156e+03, 6.250e+02, 6.084e+03, 4.225e+03, 8.100e-01])

In [37]:
a**b

array([6.94444444e-03, 9.37958786e+22, 9.31322575e+20, 8.83176087e+00,
       7.89443873e+97, 8.72796357e-03])

In [38]:
a/b

array([6.00000000e+00, 2.26666667e+00, 1.66666667e+00, 1.56000000e+02,
       1.20370370e+00, 2.00000000e-02])

In [39]:
a-b

array([-10. ,  19. ,  10. ,  77.5,  11. , -44.1])

In [40]:
a

array([-12. ,  34. ,  25. ,  78. ,  65. ,   0.9])

In [41]:
b

array([-2. , 15. , 15. ,  0.5, 54. , 45. ])

In [42]:
import numpy as np

In [43]:
a=np.array([[-2,3],[-0.5,13]])
b=np.array([[-2,3.5],[-0.5,23]])

In [44]:
a

array([[-2. ,  3. ],
       [-0.5, 13. ]])

In [45]:
b

array([[-2. ,  3.5],
       [-0.5, 23. ]])

In [46]:
a*b

array([[4.00e+00, 1.05e+01],
       [2.50e-01, 2.99e+02]])

In [47]:
a-b

array([[  0. ,  -0.5],
       [  0. , -10. ]])

In [48]:
a/b

array([[1.        , 0.85714286],
       [1.        , 0.56521739]])

In [49]:
a**b

<ipython-input-49-27166ff49cce>:1: RuntimeWarning: invalid value encountered in power
  a**b


array([[2.50000000e-01, 4.67653718e+01],
       [           nan, 4.17539054e+25]])

In [50]:
import numpy as np

In [51]:
a=np.array([-20,-3.5,25,14,2])

In [52]:
a>=10

array([False, False,  True,  True, False])

In [53]:
a<=10

array([ True,  True, False, False,  True])

In [54]:
a>=20

array([False, False,  True, False, False])

In [55]:
a<=20

array([ True,  True, False,  True,  True])

In [56]:
a[a>=10]

array([25., 14.])

In [57]:
b=np.array([-20,30,0.5])

In [60]:
c=np.array([True,False,True])

In [61]:
b[c]

array([-20. ,   0.5])