In [1]:
import numpy as np

In [2]:
np.sqrt(25)

5.0

In [3]:
np.sqrt(625)

25.0

In [4]:
np.sqrt(9)

3.0

In [5]:
np.sqrt(89)

9.433981132056603

In [6]:
nq.sqrt(-125)

NameError: name 'nq' is not defined

In [8]:
np.power(4,2)

16

In [10]:
np.power(4^2)

ValueError: invalid number of arguments

In [11]:
np.exp(9)

8103.083927575384

In [12]:
np.exp(7.89)

2670.443920676805

In [13]:
np.exp(-125)

5.166420632837861e-55

In [14]:
np.exp(8*5)

2.3538526683702e+17

In [15]:
np.exp(8/6)

3.7936678946831774

In [16]:
np.exp(5%6)

148.4131591025766

In [17]:
np.exp(8-4)

54.598150033144236

In [18]:
np.sin(180)

-0.8011526357338304

In [19]:
np.sin(90)

0.8939966636005579

In [20]:
np.sin(0)

0.0

In [21]:
np.sin(-180)

0.8011526357338304

In [22]:
np.sin(-90)

-0.8939966636005579

In [23]:
np.cos(180)

-0.5984600690578581

In [24]:
np.cos(360)

-0.2836910914865273

In [25]:
np.cos(-180)

-0.5984600690578581

In [26]:
np.cos(-90)

-0.4480736161291701

In [27]:
np.cos(-360)

-0.2836910914865273

In [28]:
np.cos(270)

0.9843819506325049

In [29]:
np.tan(180)

1.3386902103511544

In [30]:
np.tan(360)

-3.380140413960958

In [31]:
np.tan(270)

-0.17883906379845224

In [32]:
np.tan(-180)

-1.3386902103511544

In [33]:
np.tan(-360)

3.380140413960958

In [34]:
np.tan(-90)

1.995200412208242

In [35]:
np.tan(90)

-1.995200412208242

In [36]:
np.log(0.5)

-0.6931471805599453

In [37]:
np.antilog(9)

AttributeError: module 'numpy' has no attribute 'antilog'

In [38]:
np.log(-0.7)

<ipython-input-38-05d9dc7a2e9e>:1: RuntimeWarning: invalid value encountered in log
  np.log(-0.7)


nan

In [39]:
np.log(3)+np.log(4)

2.4849066497880004

In [40]:
np.log(-3)-np.log(0.5)

<ipython-input-40-c5913ef58dbe>:1: RuntimeWarning: invalid value encountered in log
  np.log(-3)-np.log(0.5)


nan

In [41]:
np.log(4)*3

4.1588830833596715

In [42]:
np.log(-25)*5

<ipython-input-42-9480aabaaad8>:1: RuntimeWarning: invalid value encountered in log
  np.log(-25)*5


nan

In [43]:
np.log(9)%4

2.1972245773362196

In [44]:
np.log(0.67)%8

7.599522433402875

In [45]:
np.log10(9)*5

4.771212547196624

In [46]:
np.log10(7)%9

0.8450980400142568

In [50]:
np.round(4.567,9)

4.567

In [51]:
np.round(9.765,-7)

0.0

In [54]:
np.e

2.718281828459045

In [57]:
np.e(4.98,5)

TypeError: 'float' object is not callable

In [60]:
np.pi

3.141592653589793

In [62]:
np.inf

inf

In [64]:
np.NINF

-inf

In [65]:
np.nan

nan

In [66]:
L=[23,34,25,89,-89,0.987]
L

[23, 34, 25, 89, -89, 0.987]

In [68]:
a=np.array(L)
a

array([ 23.   ,  34.   ,  25.   ,  89.   , -89.   ,   0.987])

In [69]:
L*3

[23,
 34,
 25,
 89,
 -89,
 0.987,
 23,
 34,
 25,
 89,
 -89,
 0.987,
 23,
 34,
 25,
 89,
 -89,
 0.987]

In [70]:
L/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [71]:
L^3

TypeError: unsupported operand type(s) for ^: 'list' and 'int'

In [72]:
a*3

array([  69.   ,  102.   ,   75.   ,  267.   , -267.   ,    2.961])

In [73]:
a%3

array([2.   , 1.   , 1.   , 2.   , 1.   , 0.987])

In [74]:
L%3

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [75]:
L1=[[2,3,4],[5,6,9],[10,25,45]]
L1

[[2, 3, 4], [5, 6, 9], [10, 25, 45]]

In [76]:
b=np.array(L1)

In [77]:
b

array([[ 2,  3,  4],
       [ 5,  6,  9],
       [10, 25, 45]])

In [78]:
L2=[[2,3,4],[5,6,9],[10,25,45]]
L2

[[2, 3, 4], [5, 6, 9], [10, 25, 45]]

In [79]:
c=np.array(L2)

In [80]:
c

array([[ 2,  3,  4],
       [ 5,  6,  9],
       [10, 25, 45]])

In [81]:
b+c

array([[ 4,  6,  8],
       [10, 12, 18],
       [20, 50, 90]])

In [82]:
b-c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
b*2-c*5

array([[  -6,   -9,  -12],
       [ -15,  -18,  -27],
       [ -30,  -75, -135]])

In [84]:
b*5+c*7

array([[ 24,  36,  48],
       [ 60,  72, 108],
       [120, 300, 540]])

In [86]:
b.shape

(3, 3)

In [87]:
b.ndim

2

In [88]:
b.dtype

dtype('int32')

In [89]:
b.size

9

In [90]:
c.shape

(3, 3)

In [91]:
c.ndim

2

In [93]:
c.dtype

dtype('int32')

In [94]:
c.size

9

In [96]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [101]:
np.zeros((1,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [102]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [103]:
np.ones((9,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [104]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [107]:
import numpy as np

In [108]:
a=np.random.randint(4,10,7)
a

array([5, 7, 7, 7, 8, 9, 6])

In [110]:
a.shape

(7,)

In [111]:
a.size

7

In [4]:
b=np.random.randint(4,10,7).reshape([2,4])
b

NameError: name 'np' is not defined

In [5]:
import random
rnum=random.randint(1,20)
unum=int(input("Enter Your number: "))
guess=[]

if unum>=1 and unum<=10:
     guess.append(unum)
        
     while unum!=rnum:
          if unum<rnum:
                print("Please Try a higher value: ")
          else:
                print("Please try a lower value: ")
                
          unum=int(input("Enter Your number: "))
          guess.append(unum)
          if len(guess)<=5:
                print("You have won!!")
          else:
                print(f"You have last. You have tried {len(guess)} times. try again.")
        
else:
    print("Restart the game and try with a number within 1 to 20.")

Enter Your number: 15
Restart the game and try with a number within 1 to 20.


In [10]:
import random
rnum=random.randint(1,20)
unum=int(input("Enter Your number: "))
guess=[]

if unum>=1 and unum<=20:
     guess.append(unum)
        
     while unum!=rnum:
          if unum<rnum:
                print("Please Try a higher value: ")
          else:
                print("Please try a lower value: ")
                
          unum=int(input("Enter Your number: "))
          guess.append(unum)
          if len(guess)<=20:
                print("You have won!!")
          else:
                print(f"You have last. You have tried {len(guess)} times. try again.")
        
else:
    print("Restart the game and try with a number within 1 to 20.")

Enter Your number: 17
Please try a lower value: 
Enter Your number: 12
You have won!!
Please try a lower value: 
Enter Your number: 10
You have won!!
Please try a lower value: 
Enter Your number: 9
You have won!!
