In [1]:
import numpy as np

In [2]:
o=np.array([-2,3.45,8,5,6])

In [3]:
o

array([-2.  ,  3.45,  8.  ,  5.  ,  6.  ])

In [4]:
o+100

array([ 98.  , 103.45, 108.  , 105.  , 106.  ])

In [5]:
o-100

array([-102.  ,  -96.55,  -92.  ,  -95.  ,  -94.  ])

In [7]:
o*100

array([-200.,  345.,  800.,  500.,  600.])

In [8]:
o**100

array([1.26765060e+30, 6.05214755e+53, 2.03703598e+90, 7.88860905e+69,
       6.53318624e+77])

In [9]:
o.T

array([-2.  ,  3.45,  8.  ,  5.  ,  6.  ])

In [14]:
m=np.array([[1,2,9/10],[2,3,-2.56]])
m

array([[ 1.  ,  2.  ,  0.9 ],
       [ 2.  ,  3.  , -2.56]])

In [18]:
np.transpose(m)

array([[ 1.  ,  2.  ],
       [ 2.  ,  3.  ],
       [ 0.9 , -2.56]])

In [19]:
m.T

array([[ 1.  ,  2.  ],
       [ 2.  ,  3.  ],
       [ 0.9 , -2.56]])

In [20]:
np.trace(m)

4.0

In [21]:
np.trace(m.T)

4.0

In [22]:
np.diag(m)

array([1., 3.])

In [23]:
o%2==0

array([ True, False,  True, False,  True])

In [28]:
o%3==0

array([False, False, False, False,  True])

In [29]:
m%2==0

array([[False,  True, False],
       [ True, False, False]])

In [30]:
m%3==0

array([[False, False, False],
       [False,  True, False]])

In [31]:
import numpy as np

In [32]:
o=np.array([-2,3.45,8,5,6])

In [33]:
o

array([-2.  ,  3.45,  8.  ,  5.  ,  6.  ])

In [35]:
o%2==0

array([ True, False,  True, False,  True])

In [38]:
np.where(o%2==0,o*100,o)

array([-200.  ,    3.45,  800.  ,    5.  ,  600.  ])

In [39]:
o.min()

-2.0

In [40]:
o.max()

8.0

In [41]:
o.mean()

4.09

In [43]:
o.sort()

In [44]:
o

array([-2.  ,  3.45,  5.  ,  6.  ,  8.  ])

In [45]:
o.sum()

20.45

In [46]:
np.mean(o)

4.09

In [47]:
np.min(o)

-2.0

In [48]:
np.max(o)

8.0

In [49]:
np.median(o)

5.0

In [50]:
m=np.array([[1,2,9/10],[2,3,-2.56]])
m

array([[ 1.  ,  2.  ,  0.9 ],
       [ 2.  ,  3.  , -2.56]])

In [51]:
n=np.array([[1,-2,9/10],[2,3.65,-2.56]])
n

array([[ 1.  , -2.  ,  0.9 ],
       [ 2.  ,  3.65, -2.56]])

In [52]:
np.append(m,n,axis=0)

array([[ 1.  ,  2.  ,  0.9 ],
       [ 2.  ,  3.  , -2.56],
       [ 1.  , -2.  ,  0.9 ],
       [ 2.  ,  3.65, -2.56]])

In [53]:
np.append(m,n,axis=-1)

array([[ 1.  ,  2.  ,  0.9 ,  1.  , -2.  ,  0.9 ],
       [ 2.  ,  3.  , -2.56,  2.  ,  3.65, -2.56]])

In [54]:
np.append(m,n,axis=1)

array([[ 1.  ,  2.  ,  0.9 ,  1.  , -2.  ,  0.9 ],
       [ 2.  ,  3.  , -2.56,  2.  ,  3.65, -2.56]])

In [56]:
import numpy as np

In [58]:
a=np.random.random((-3,8))
a

ValueError: negative dimensions are not allowed

In [60]:
a=np.random.random((3,8))
a

array([[0.88010944, 0.09267543, 0.42632974, 0.04083721, 0.12063436,
        0.18302219, 0.70660739, 0.56309986],
       [0.99688846, 0.95834808, 0.05495957, 0.79997714, 0.94542435,
        0.5097852 , 0.27146315, 0.67931821],
       [0.68973174, 0.12927585, 0.34161544, 0.46509051, 0.53002707,
        0.64026711, 0.33989577, 0.02862787]])

In [63]:
b=np.hsplit(a,8)
b

[array([[0.88010944],
        [0.99688846],
        [0.68973174]]),
 array([[0.09267543],
        [0.95834808],
        [0.12927585]]),
 array([[0.42632974],
        [0.05495957],
        [0.34161544]]),
 array([[0.04083721],
        [0.79997714],
        [0.46509051]]),
 array([[0.12063436],
        [0.94542435],
        [0.53002707]]),
 array([[0.18302219],
        [0.5097852 ],
        [0.64026711]]),
 array([[0.70660739],
        [0.27146315],
        [0.33989577]]),
 array([[0.56309986],
        [0.67931821],
        [0.02862787]])]

In [64]:
np.roll(a,0)

array([[0.88010944, 0.09267543, 0.42632974, 0.04083721, 0.12063436,
        0.18302219, 0.70660739, 0.56309986],
       [0.99688846, 0.95834808, 0.05495957, 0.79997714, 0.94542435,
        0.5097852 , 0.27146315, 0.67931821],
       [0.68973174, 0.12927585, 0.34161544, 0.46509051, 0.53002707,
        0.64026711, 0.33989577, 0.02862787]])

In [65]:
a.astype(float)

array([[0.88010944, 0.09267543, 0.42632974, 0.04083721, 0.12063436,
        0.18302219, 0.70660739, 0.56309986],
       [0.99688846, 0.95834808, 0.05495957, 0.79997714, 0.94542435,
        0.5097852 , 0.27146315, 0.67931821],
       [0.68973174, 0.12927585, 0.34161544, 0.46509051, 0.53002707,
        0.64026711, 0.33989577, 0.02862787]])

In [66]:
L=[2,3,4,8,-9]

In [67]:
[str(i) for i in L]

['2', '3', '4', '8', '-9']

In [68]:
list(map(str,L))

['2', '3', '4', '8', '-9']

In [69]:
print("imesh: Hello I am imesh. What is your Name?")
name=input("Your Name :")
print(f"imesh: Hi(name)...so what do you want to know about our company?")
ans=input("Your answer :")

if all(i in ans.lower().split(" ") for i in ["company","name"]):
    print("imesh: our company is Leeza(PVT)Ltd")

imesh: Hello I am imesh. What is your Name?
Your Name :imesh
imesh: Hi(name)...so what do you want to know about our company?
Your answer :Leeza(PVT)Ltd


In [121]:
print("imesh: Hello I am imesh. What is your Name?")
name=input("Your Name :")
print(f"imesh: Hi(name)...so what do you want to know about our company?")
ans=input("Your answer :")

flag=True

while flag:

   if all(i in ans.lower().split(" ") for i in ["company","name"]):
      print("imesh: our company is Leeza(PVT)Ltd")
      print("imesh: Do you want to know anything else?")
      check=input("Your answer:")
      if any(i in check.lower().split(" ") for i in ["yes","yeah","exactly","sure"]):
          print("imesh: okay, what do you want to know?")
          ans=input("Your answer:")
          flag=True
      else:
          print(f"imesh: okay(name). Nice to chat with you. Have a nice day")
          flag=False
    
   elif all(i in ans.lower().split(" ") for i in ["ceo"]):
    print("imesh: our CEO is Mr.Lazy Peter")
    
   elif any(i in ans.lower().split(" ") for i in ["address","location","place","located","where"]):
    print("imesh: our address is 175 Kaduwela Road, Malabe")
    
   elif any(i in ans.lower().split(" ") for i in ["Contact","Telephone","email","telephone number"]):
    print("imesh: Contact us. Our email:harsha345@gmail.com, Our telephone number:0112874646")
    print("imesh: Do you want to know anything else?")
    check=input("Your answer:")
    if any(i in check.lower().split(" ") for i in ["yes","yeah","exactly","sure"]):
          print("imesh: okay, what do you want to know?")
          ans=input("Your answer:")
          flag=True   
   else:
          print(f"imesh: okay(name). Nice to chat with you. Have a nice day")
          flag=False 
   else:
          print("imesh: Sorry[name], I can't understand your question")
          print("imesh: Do you want to know anything else?")
   check=input("Your answer:")
      if any(i in check.lower().split(" ") for i in ["yes","yeah","exactly","sure"]):
          print("imesh: okay, what do you want to know?")
          ans=input("Your answer:")
          flag=True
   else:
          print(f"imesh: okay(name). Nice to chat with you. Have a nice day")
          flag=False

SyntaxError: invalid syntax (<ipython-input-121-ac30beb262a6>, line 39)